# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-06 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20181106_1521'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'user')]),
        ),
    ]
