# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-06 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181106_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='database_built',
            field=models.BooleanField(default=False),
        ),
    ]
