# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_database_built'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('ssh_username', models.CharField(max_length=64)),
                ('ssh_password', models.CharField(max_length=256)),
                ('server_address', models.CharField(max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
            options={
                'verbose_name_plural': 'Databases',
            },
        ),
        migrations.CreateModel(
            name='DatabaseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Database')),
            ],
            options={
                'verbose_name_plural': 'Database Tables',
            },
        ),
    ]
