# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_database_databasetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DatabaseTable')),
            ],
            options={
                'verbose_name_plural': 'Database Columns',
            },
        ),
    ]
