# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_databasecolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('request_type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=4)),
                ('endpoint_url', models.CharField(max_length=64, unique=True)),
                ('response_format', models.CharField(choices=[('JSON', 'JSON'), ('XML', 'XML')], max_length=4)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
            options={
                'verbose_name_plural': 'Endpoints',
            },
        ),
        migrations.CreateModel(
            name='EndpointDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'Database'), ('T', 'Text')], max_length=1)),
                ('table_name', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Endpoint Datasources',
            },
        ),
        migrations.CreateModel(
            name='EndpointDataSourceColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Endpoint')),
            ],
            options={
                'verbose_name_plural': 'Endpoint Data Source Columns',
            },
        ),
        migrations.CreateModel(
            name='EndpointHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Endpoint')),
            ],
            options={
                'verbose_name_plural': 'Endpoint Headers',
            },
        ),
        migrations.CreateModel(
            name='EndpointParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Endpoint')),
            ],
            options={
                'verbose_name_plural': 'Endpoint Parameters',
            },
        ),
    ]
