# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_endpoint_endpointdatasource_endpointdatasourcecolumn_endpointheader_endpointparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointparameter',
            name='type',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
