# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_endpointparameter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
