# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-29 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190129_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=25, null=True),
        ),
    ]
