# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-29 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_apikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='name',
            new_name='key',
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
