# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-05 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_apikey_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointDataSourceFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GET', 'GET Parameter'), ('POST', 'POST Parameter')], max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Endpoint Data Source Filters',
            },
        ),
        migrations.RemoveField(
            model_name='endpointdatasourcecolumn',
            name='name',
        ),
        migrations.AddField(
            model_name='endpointdatasourcecolumn',
            name='column_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endpointdatasourcefilter',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EndpointDataSourceColumn'),
        ),
        migrations.AddField(
            model_name='endpointdatasourcefilter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EndpointParameter'),
        ),
    ]
