# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-06 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190205_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpointdatasourcefilter',
            old_name='column',
            new_name='column_parameter',
        ),
        migrations.RenameField(
            model_name='endpointdatasourcefilter',
            old_name='parameter',
            new_name='request_parameter',
        ),
    ]
