# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-06 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190206_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointdatasourcefilter',
            name='column_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EndpointDataSourceColumn'),
        ),
        migrations.AlterField(
            model_name='endpointdatasourcefilter',
            name='request_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EndpointParameter'),
        ),
    ]
