# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190206_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointdatasourcefilter',
            name='column_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DatabaseColumn'),
        ),
        migrations.AlterField(
            model_name='endpointparameter',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
