# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-07 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_endpointdatasourcefilter_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
