# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-13 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_endpoint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='database',
            name='ssh_username',
        ),
    ]
