# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-14 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190214_1130'),
        ('core', '0023_auto_20190213_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='project',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='user',
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
