# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-14 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190214_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='endpoint_limit',
            new_name='resource_limit',
        ),
        migrations.RenameField(
            model_name='endpoint',
            old_name='endpoint_url',
            new_name='resource_url',
        ),
        migrations.RenameField(
            model_name='endpointdatasourcecolumn',
            old_name='endpoint',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='endpointdatasourcefilter',
            old_name='endpoint',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='endpointheader',
            old_name='endpoint',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='endpointparameter',
            old_name='endpoint',
            new_name='resource',
        ),
    ]
