# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-14 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190214_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endpoint',
            new_name='Resource',
        ),
        migrations.RenameModel(
            old_name='EndpointDataSource',
            new_name='ResourceDataSource',
        ),
        migrations.RenameModel(
            old_name='EndpointDataSourceColumn',
            new_name='ResourceDataSourceColumn',
        ),
        migrations.RenameModel(
            old_name='EndpointDataSourceFilter',
            new_name='ResourceDataSourceFilter',
        ),
        migrations.RenameModel(
            old_name='EndpointHeader',
            new_name='ResourceHeader',
        ),
        migrations.RenameModel(
            old_name='EndpointParameter',
            new_name='ResourceParameter',
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='resourcedatasource',
            options={'verbose_name_plural': 'Resource Datasources'},
        ),
        migrations.AlterModelOptions(
            name='resourcedatasourcecolumn',
            options={'verbose_name_plural': 'Resource Data Source Columns'},
        ),
        migrations.AlterModelOptions(
            name='resourcedatasourcefilter',
            options={'verbose_name_plural': 'Resource Data Source Filters'},
        ),
        migrations.AlterModelOptions(
            name='resourceheader',
            options={'verbose_name_plural': 'Resource Headers'},
        ),
        migrations.AlterModelOptions(
            name='resourceparameter',
            options={'verbose_name_plural': 'Resource Parameters'},
        ),
    ]
