# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-14 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190214_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedatasourcefilter',
            name='column_to_filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='column_to_filter_with_this_filter', to='core.DatabaseColumn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcedatasourcefilter',
            name='column_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column_to_act_as_filter', to='core.DatabaseColumn'),
        ),
    ]
