# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-16 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190216_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceparentchildrelationship',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Resource'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourceparameter',
            name='key',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='resourceheader',
            unique_together=set([('key', 'resource')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourceparameter',
            unique_together=set([('key', 'resource')]),
        ),
    ]
