# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-16 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190216_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceparentchildrelationship',
            name='resource',
        ),
    ]
