# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-16 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_resourceparentchildrelationship_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceparentchildrelationship',
            name='resource',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='core.Resource'),
            preserve_default=False,
        ),
    ]
