# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-16 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_resourceparentchildrelationship_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceparentchildrelationship',
            name='child_table',
        ),
        migrations.RemoveField(
            model_name='resourceparentchildrelationship',
            name='child_table_column',
        ),
        migrations.RemoveField(
            model_name='resourceparentchildrelationship',
            name='parent_table',
        ),
        migrations.RemoveField(
            model_name='resourceparentchildrelationship',
            name='parent_table_column',
        ),
        migrations.RemoveField(
            model_name='resourceparentchildrelationship',
            name='resource',
        ),
        migrations.DeleteModel(
            name='ResourceParentChildRelationship',
        ),
    ]
