# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-22 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_resourceparentchildrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
            options={
                'verbose_name_plural': 'Blocked IPs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='blockedip',
            unique_together=set([('ip_address', 'project')]),
        ),
    ]
