# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-25 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20190222_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDataBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DatabaseColumn')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Resource')),
            ],
            options={
                'verbose_name_plural': 'Resource Data Binds',
            },
        ),
        migrations.AlterUniqueTogether(
            name='resourcedatabind',
            unique_together=set([('key', 'resource')]),
        ),
    ]
