# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-26 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20190225_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='type',
            field=models.CharField(choices=[('Integer', 'Integer: Positive or Negative whole number'), ('Decimal', 'Decimal: Positive or Negative number with decimal'), ('String', 'String: Text'), ('Boolean', 'Boolean: True or False')], default=1, max_length=32),
            preserve_default=False,
        ),
    ]
