# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20190226_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedatabind',
            name='type',
            field=models.CharField(choices=[('Integer', 'Integer'), ('Decimal', 'Decimal'), ('String', 'String'), ('Boolean', 'Boolean')], max_length=32),
        ),
    ]
