# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-11 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20190227_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='caching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='caching_expiry',
            field=models.CharField(blank=True, choices=[('1', '1 Hour'), ('2', '2 Hours'), ('4', '4 Hours'), ('8', '8 Hours'), ('12', '12 Hours'), ('24', '14 Hours')], max_length=2, null=True),
        ),
    ]
