# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-27 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20190311_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
            options={
                'verbose_name_plural': 'User Groups',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together=set([('name', 'project')]),
        ),
    ]
