# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-27 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20190327_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Resource')),
            ],
            options={
                'verbose_name_plural': 'Resource User Groups',
            },
        ),
        migrations.AlterUniqueTogether(
            name='resourceusergroup',
            unique_together=set([('name', 'resource')]),
        ),
    ]
