# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-27 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20190327_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceusergroup',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.UserGroup'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='resourceusergroup',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='resourceusergroup',
            unique_together=set([('user_group', 'resource')]),
        ),
    ]
