# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-27 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20190327_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Resource')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserGroup')),
            ],
            options={
                'verbose_name_plural': 'Resource User Groups',
            },
        ),
    ]
