# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-04 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_account_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='demo',
            field=models.BooleanField(default=True),
        ),
    ]
