# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20190404_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='forgot_password_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
