# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-07 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_account_forgot_password_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='forgot_password_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
