# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-07 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20190407_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='period',
            field=models.CharField(choices=[('day', 'In one day'), ('week', 'In one week'), ('month', 'In one month'), ('year', 'In one year'), ('forever', 'In all time')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
