# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-07 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alert_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notification_sent_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
