# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-14 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_auto_20190213_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication_type', models.CharField(choices=[('KEY', 'Request was authorised by API key'), ('NO_AUTH', 'Request was not authorised.')], max_length=10)),
                ('type', models.CharField(choices=[('GET', 'GET Request'), ('POST', 'POST Request')], max_length=6)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('200 OK', '200 OK - Request was fine'), ('400 ERR', '400 ERR - The request was incorrect.'), ('401 ERR', '401 ERR - No API key or the provided key is invalid.')], max_length=8)),
                ('ip_address', models.GenericIPAddressField()),
                ('source', models.CharField(max_length=256)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.APIKey')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Endpoint')),
            ],
            options={
                'verbose_name_plural': 'API Requests',
            },
        ),
    ]
