# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-14 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190214_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='status',
            field=models.CharField(choices=[('200 OK', '200 OK - Request was fine'), ('400 ERR', '400 ERR - The request was incorrect.'), ('401 ERR', '401 ERR - No API key or the provided key is invalid.'), ('404 ERR', '404 ERR - The requested resource does not exist.')], max_length=8),
        ),
    ]
