# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-18 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190214_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='resource',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
