# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190226_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='response_to_user',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
