# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_apirequest_response_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='cached_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='status',
            field=models.CharField(choices=[('200 OK', '200 OK - Request was fine.'), ('400 ERR', '400 ERR - The request was incorrect.'), ('401 ERR', '401 ERR - No API key or the provided key is invalid.'), ('402 ERR', '402 ERR - The parameters were valid but the request failed.'), ('403 ERR', '403 ERR - The request is forbidden.'), ('404 ERR', '404 ERR - The requested resource does not exist.')], max_length=8),
        ),
    ]
