# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-18 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190311_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='cache',
            field=models.BooleanField(default=False),
        ),
    ]
