# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20190327_1116'),
        ('api', '0010_apirequest_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserGroup'),
        ),
    ]
