# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0037_resourceparentchildrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_text', models.TextField(blank=True, null=True)),
                ('support_email', models.CharField(max_length=256)),
                ('navbar_colour', models.CharField(blank=True, default='FFFFFF', max_length=6, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/docs/images/docs-logos')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
            options={
                'verbose_name_plural': 'Documentation Instances',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguageChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('curl', 'curl'), ('Python', 'Python')], max_length=32)),
                ('documentation_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.DocumentationInstance')),
            ],
            options={
                'verbose_name_plural': 'Programming Language Choices',
            },
        ),
        migrations.AlterUniqueTogether(
            name='programminglanguagechoice',
            unique_together=set([('name', 'documentation_instance')]),
        ),
    ]
