# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-20 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationinstance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project', unique=True),
        ),
        migrations.AlterField(
            model_name='documentationinstance',
            name='support_email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
