# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-20 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_documentationinstance_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguagechoice',
            name='name',
            field=models.CharField(choices=[('curl', 'curl'), ('python', 'Python')], max_length=32),
        ),
    ]
