# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-20 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20190220_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationinstance',
            name='navbar_colour',
            field=models.CharField(blank=True, default='FFFFFF', max_length=7, null=True),
        ),
    ]
